version: "3"

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      #- ZOO_SERVER_ID = 101
      - ALLOW_ANONYMOUS_LOGIN = yes
      - ZOOKEEPER_CLIENT_PORT = 2181
      - ZOOKEEPER_TICK_TIME = 2000
      -
  broker:
    image: confluentinc/cp-server:5.5.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID = 1
      - KAFKA_ZOOKEEPER_CONNECT = 'zookeeper:2181'
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS = INTERNAL://broker:29092,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP = INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
#METRIC/ADDITIONAL CONFIG
      - KAFKA_METRIC_REPORTERS = io.confluent.metrics.reporter.ConfluentMetricsReporter
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR = 1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS = 0
      - KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR = 1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR = 1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR = 1
      - CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS = broker:29092
      - CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT = zookeeper:2181
      - CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS = 1
      - CONFLUENT_METRICS_ENABLE = 'true'
      - CONFLUENT_SUPPORT_CUSTOMER_ID = 'anonymous'


  connect:
    image: cnfldemos/cp-server-connect-datagen:0.3.2-5.5.0
    hostname: connect
    container_name: connect
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8083:8083"
    environment:
        - CONNECT_BOOTSTRAP_SERVERS = 'broker:29092'
        - CONNECT_GROUP_ID = connect-group
        - CONNECT_REST_ADVERTISED_HOST_NAME=localhost
        - CONNECT_REST_PORT = 8083
        - CONNECT_CONFIG_STORAGE_TOPIC = connect-config
        - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR = 1
        - CONNECT_OFFSET_STORAGE_TOPIC = docker-connect-offsets
        - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR = 1
        - CONNECT_OFFSET_FLUSH_INTERVAL_MS = 10000
        - CONNECT_STATUS_STORAGE_TOPIC = connect-status
        - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR = 1
        - CONNECT_KEY_CONVERTER = org.apache.kafka.connect.storage.StringConverter
        - CONNECT_VALUE_CONVERTER = io.confluent.connect.avro.AvroConverter
        - CONNECT_INTERNAL_KEY_CONVERTER = "org.apache.kafka.connect.json.JsonConverter"
        - CONNECT_INTERNAL_VALUE_CONVERTER = "org.apache.kafka.connect.json.JsonConverter"
        - CONNECT_ZOOKEEPER_CONNECT = 'zookeeper:2181'
        # CLASSPATH required due to CC-2422
        - CLASSPATH = /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.5.1.jar
        - CONNECT_PRODUCER_INTERCEPTOR_CLASSES = "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
        - CONNECT_CONSUMER_INTERCEPTOR_CLASSES = "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
        - CONNECT_PLUGIN_PATH = "/usr/share/java,/usr/share/confluent-hub-components"
        - CONNECT_LOG4J_LOGGERS = org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
